language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - pip install -e git+https://github.com/pdef/pdef.git@1.1#egg=pdef-compiler==1.1
install:
  - sh -c 'cd generator && python setup.py install'
  - sh -c 'cd python && python setup.py install'
script:
  - sh -c 'cd generator && nosetests'
  - sh -c 'cd python && ./gen-pdef && nosetests'
